export const data = [
    {
        "id": 1,
        "name": "Charlie Kristen",
        "rating": "4.0",
        "stages": "Design Challenge",
        "applied_role": "Sr. UX DEsigner",
        "application_date": "12/02/23",
        "attachments": "3 files",
        "accepted": true,
    },
    {
        "id": 2,
        "name": "Malaika Brown",
        "rating": "3.5",
        "stages": "Screening",
        "applied_role": "Growth Manager",
        "application_date": "18/02/23",
        "attachments": "1 files",
        "accepted": false,
    },
    {
        "id": 3,
        "name": "Simon Minter",
        "rating": "2.8",
        "stages": "Design Challenge",
        "applied_role": "Financial Analyst",
        "application_date": "04/01/23",
        "attachments": "2 files",
        "accepted": false,
    },
    {
        "id": 4,
        "name": "Ashley Brooke",
        "rating": "4.5",
        "stages": "HR Round",
        "applied_role": "Financial Analyst",
        "application_date": "05/03/23",
        "attachments": "3 files",
        "accepted": true,
    },
]